# -*- coding: utf-8 -*-
"""Flavor Sensor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdK9ekafc90GrnoyK-zi3slF-v8ZkWDj

**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

df = pd.read_csv("FlavorSense.csv")

"""**Data Exploration**"""

df

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

"""**Outlier Detection**"""

plt.figure(figsize=(8,5))
sns.boxplot(data=df.select_dtypes(include=['int64','float64']))
plt.title("Box Plot of Numerical Features", fontsize=16, fontweight="bold")
plt.xlabel("Numerical Features", fontsize=12)
plt.ylabel("Values", fontsize=12)
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

# Fill Numerical Missing Values using Median
df.fillna(df.median(numeric_only=True), inplace=True)
# Fill Categorical Missing Values using Mode
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna(df[col].mode()[0])
# Check Missing Values
df.isnull().sum()

"""**Count Plot(Target Distribution)**"""

df.columns

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))

sns.countplot(
    x="preferred_taste",
    hue="preferred_taste",
    data=df,
    palette="Set2",
    legend=False
)

plt.title("Target Class Distribution", fontsize=16, fontweight="bold")
plt.xlabel("Preferred Taste", fontsize=12)
plt.ylabel("Count", fontsize=12)

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()

"""**Histogram**"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(9,5))
sns.histplot(
    data=df,
    x="age",
    bins=20,
    kde=True,
    color="steelblue",
    edgecolor="black",
    alpha=0.8
)
plt.title("Distribution of Age", fontsize=16, fontweight="bold")
plt.xlabel("Age", fontsize=12, fontweight="bold")
plt.ylabel("Frequency", fontsize=12, fontweight="bold")
plt.grid(axis="y", linestyle="--", alpha=0.5)
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
plt.tight_layout()
plt.show()

"""**Data Preprocessing**"""

df.duplicated().sum()

# Remove Duplicate Rows
df.drop_duplicates(inplace=True)
# Verify
df.duplicated().sum()

df.shape

"""**Encoding**"""

categorical_columns = [
    "sleep_cycle",
    "exercise_habits",
    "climate_zone",
    "historical_cuisine_exposure"
]
df = pd.get_dummies(
    df,
    columns=categorical_columns,
    dtype=int
)
print("Dataset Shape :", df.shape)
display(df.head())

"""**Target Encoding**"""

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["preferred_taste"] = encoder.fit_transform(df["preferred_taste"])
print(df["preferred_taste"].head())

df

"""**Feature Selection**"""

X = df.drop("preferred_taste", axis=1)
y = df["preferred_taste"]
print("Features Shape :", X.shape)
print("Target Shape   :", y.shape)
print("\nFeatures")
display(X.head())
print("\nTarget")
display(y.head())

"""Feature Scaling (Standardization)"""

# Features
X = df.drop("preferred_taste", axis=1)
# Target
y = df["preferred_taste"]
# Mean
mean = X.mean()
# Standard Deviation
std = X.std()
# Standardization
X = (X - mean) / std
# Display First 5 Rows
X.head()

"""**Correlation Heatmap**"""

plt.figure(figsize=(12,8))
correlation = df.corr(numeric_only=True)
sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
    linewidths=0.5
)
plt.title("Correlation Heatmap", fontsize=16, fontweight="bold")
plt.tight_layout()
plt.show()

"""**Train-Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,random_state=42)
print("X_train Shape :", X_train.shape)
print("X_test Shape :", X_test.shape)
print("y_train Shape :", y_train.shape)
print("y_test Shape :", y_test.shape)

"""**KNN From Scratch**"""

# Euclidean Distance
def euclidean_distance(x1, x2):
    distance = np.sqrt(np.sum((x1 - x2) ** 2))
    return distance

"""Test the Function"""

# First Training Sample
point1 = X_train.iloc[0].values
# Second Training Sample
point2 = X_train.iloc[1].values
# Euclidean Distance Function
def euclidean_distance(x1, x2):
    distance = np.sqrt(np.sum((x1 - x2) ** 2))
    return distance
# Calculate Distance
distance = euclidean_distance(point1, point2)
# Display Result
print("Euclidean Distance:", distance)

"""**Euclidean Distance Visualization**"""

# Two Points
point1 = np.array([2, 3])
point2 = np.array([5, 7])
# Calculate Euclidean Distance
distance = np.sqrt(np.sum((point2 - point1) ** 2))
# Create Figure
plt.figure(figsize=(8,6))
# Plot Points
plt.scatter(point1[0], point1[1], color="blue", s=150, label="Point A")
plt.scatter(point2[0], point2[1], color="red", s=150, label="Point B")
# Draw Line Between Points
plt.plot(
    [point1[0], point2[0]],
    [point1[1], point2[1]],
    color="green",
    linestyle="--",
    linewidth=2,
    label="Euclidean Distance"
)
# Labels for Points
plt.text(point1[0]-0.3, point1[1]-0.3, "A", fontsize=12, fontweight="bold")
plt.text(point2[0]+0.1, point2[1], "B", fontsize=12, fontweight="bold")
# Display Distance on Graph
mid_x = (point1[0] + point2[0]) / 2
mid_y = (point1[1] + point2[1]) / 2
plt.text(
    mid_x,
    mid_y,
    f"Distance = {distance:.2f}",
    fontsize=11,
    bbox=dict(facecolor="white", edgecolor="black")
)
# Formatting
plt.title("Euclidean Distance Between Two Points", fontsize=16, fontweight="bold")
plt.xlabel("X-axis", fontsize=12)
plt.ylabel("Y-axis", fontsize=12)
plt.xlim(0, 7)
plt.ylim(0, 8)
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend()
plt.show()
# Print Distance
print("Euclidean Distance =", round(distance, 2))

"""**Find K Nearest Neighbors**"""

import numpy as np

class KNN:

    # Euclidean Distance
    def euclidean_distance(self, x1, x2):
        distance = np.sqrt(np.sum((x1 - x2) ** 2))
        return distance

    # Find K Nearest Neighbors
    def get_neighbors(self, X_train, test_point, k):

        # Convert DataFrame to NumPy Array (if needed)
        X_train = np.array(X_train)
        test_point = np.array(test_point)

        distances = []

        for train_point in X_train:

            distance = self.euclidean_distance(test_point, train_point)

            distances.append(distance)

        distances = np.array(distances)

        k_indices = np.argsort(distances)[:k]

        return k_indices

"""**Test Code**"""

knn = KNN()

sample_X_train = np.array([
    [2,3],
    [5,4],
    [9,6],
    [4,7],
    [8,1],
    [7,2]
])

sample_test_point = np.array([5,5])

neighbors = knn.get_neighbors(sample_X_train, sample_test_point, k=3)

print("Nearest Neighbor Indexes :", neighbors)

"""**Graph Visualization**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

# All Training Points
plt.scatter(
    sample_X_train[:,0],
    sample_X_train[:,1],
    s=100,
    color="blue",
    label="Training Points"
)

# Query Point
plt.scatter(
    sample_test_point[0],
    sample_test_point[1],
    color="red",
    marker="*",
    s=250,
    label="Query Point"
)

# Highlight K Nearest Neighbors
plt.scatter(
    sample_X_train[neighbors,0],
    sample_X_train[neighbors,1],
    color="green",
    s=180,
    label="K Nearest Neighbors"
)

# Draw Distance Lines
for index in neighbors:

    plt.plot(
        [sample_test_point[0], sample_X_train[index,0]],
        [sample_test_point[1], sample_X_train[index,1]],
        'k--',
        linewidth=1.5
    )

plt.title("K Nearest Neighbors", fontsize=16, fontweight="bold")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend()
plt.show()

"""**Find Neighbors**"""

class KNN:

    def euclidean_distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))

    def get_neighbors(self, X_train, test_point, k):

        distances = []

        for train_point in X_train:

            distance = self.euclidean_distance(test_point, train_point)

            distances.append(distance)

        k_indices = np.argsort(distances)[:k]

        return k_indices

    def get_labels(self, y_train, k_indices):

        k_labels = []

        for index in k_indices:
            k_labels.append(y_train[index])

        return k_labels

"""Test Code"""

knn = KNN()

neighbors = knn.get_neighbors(
    sample_X_train,
    sample_test_point,
    k=3
)

print(neighbors)

"""Target Labels"""

def get_labels(y_train, k_indices):

    k_labels = []

    for index in k_indices:
        k_labels.append(int(y_train[index]))

    return k_labels

"""**Test Code**"""

sample_y_train = np.array([0, 1, 0, 1, 2, 2])

k_indices = np.array([1, 3, 2])

labels = get_labels(sample_y_train, k_indices)

print("Target Labels :", labels)

""" **Majority Voting**

"""

def majority_vote(k_labels):

    prediction = max(set(k_labels), key=k_labels.count)

    return prediction

"""**Test**"""

k_labels = [1, 1, 0]

prediction = majority_vote(k_labels)

print("Neighbor Labels :", k_labels)
print("Predicted Class :", prediction)

import matplotlib.pyplot as plt
from collections import Counter

k_labels = [1, 1, 0]

vote_count = Counter(k_labels)

plt.figure(figsize=(6,6))

plt.pie(
    vote_count.values(),
    labels=[f"Class {label}" for label in vote_count.keys()],
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Majority Voting in KNN", fontsize=16, fontweight="bold")

plt.show()

"""**Another Test**"""

k_labels = [2, 2, 1, 2, 0]

prediction = majority_vote(k_labels)

print("Neighbor Labels :", k_labels)
print("Predicted Class :", prediction)

"""**Majority Voting Visualization**"""

import matplotlib.pyplot as plt
from collections import Counter

# Neighbor Labels
k_labels = [1, 1, 0]

# Count Votes
vote_count = Counter(k_labels)

# Find Winning Class
winner = max(vote_count, key=vote_count.get)

# Colors (Winner = Green, Others = Sky Blue)
colors = []

for label in vote_count.keys():
    if label == winner:
        colors.append("limegreen")
    else:
        colors.append("skyblue")

# Create Figure
plt.figure(figsize=(8,6))

bars = plt.bar(
    [f"Class {label}" for label in vote_count.keys()],
    vote_count.values(),
    color=colors,
    edgecolor="black",
    linewidth=2,
    width=0.6
)

# Show Vote Count on Each Bar
for bar in bars:

    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.05,
        f"{int(height)}",
        ha="center",
        fontsize=12,
        fontweight="bold"
    )

# Highlight Winner
for label, bar in zip(vote_count.keys(), bars):

    if label == winner:

        plt.text(
            bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.35,
            "Winner",
            ha="center",
            color="green",
            fontsize=12,
            fontweight="bold"
        )

# Title
plt.title(
    "Majority Voting in KNN",
    fontsize=18,
    fontweight="bold"
)

# Axis Labels
plt.xlabel(
    "Class Labels",
    fontsize=13,
    fontweight="bold"
)

plt.ylabel(
    "Number of Votes",
    fontsize=13,
    fontweight="bold"
)

# Grid
plt.grid(
    axis="y",
    linestyle="--",
    alpha=0.5
)

# Y-axis Limit
plt.ylim(0, max(vote_count.values()) + 1)

# Show Plot
plt.show()

"""**KNN Class**"""

class KNN:
    def __init__(self, k=3):
        self.k = k
    def fit(self, X_train, y_train):
        self.X_train = np.array(X_train)
        self.y_train = np.array(y_train)
    def euclidean_distance(self, x1, x2):
        distance = np.sqrt(np.sum((x1 - x2) ** 2))
        return distance
    def get_neighbors(self, test_point):
        distances = []
        for train_point in self.X_train:
            distance = self.euclidean_distance(test_point, train_point)
            distances.append(distance)
        k_indices = np.argsort(distances)[:self.k]
        return k_indices

    # Get Target Labels
    def get_labels(self, k_indices):
        k_labels = []
        for index in k_indices:
            k_labels.append(int(self.y_train[index]))
        return k_labels
    # Majority Voting
    def majority_vote(self, k_labels):
        prediction = max(set(k_labels), key=k_labels.count)
        return prediction
    # Predict
    def predict(self, X_test):
        predictions = []
        X_test = np.array(X_test)
        for test_point in X_test:
            k_indices = self.get_neighbors(test_point)
            k_labels = self.get_labels(k_indices)
            prediction = self.majority_vote(k_labels)
            predictions.append(prediction)
        return np.array(predictions)

"""**Test**"""

knn = KNN(k=3)
# Train Model
knn.fit(X_train, y_train)
# Predict
y_pred = knn.predict(X_test)
print("Predictions:")
print(y_pred[:10])

"""**Train KNN Model**"""

knn = KNN(k=3)
knn.fit(X_train, y_train)
print("K Value :", knn.k)
print("Training Samples :", len(X_train))
print("Training Labels :", len(y_train))
print("Model Status : Trained Successfully")

"""**Predictions**"""

# Predict Test Data
y_pred = knn.predict(X_test)
y_pred = np.array(y_pred)
print("Predictions")
print(y_pred)
print("\nFirst 10 Predictions")
print(y_pred[:10])
# Compare Actual vs Predicted Labels
comparison = pd.DataFrame({
    "Actual Label": y_test,
    "Predicted Label": y_pred
})
print("\nActual vs Predicted")
print(comparison.head(10))
# Total Predictions
print("\nTotal Predictions :", len(y_pred))

"""**Prediction Distribution**"""



from collections import Counter
prediction_count = Counter(y_pred)
classes = [f"Class {i}" for i in prediction_count.keys()]
counts = list(prediction_count.values())
colors = ["#4CAF50", "#2196F3", "#FF9800", "#9C27B0", "#F44336"]
plt.figure(figsize=(8,6))
bars = plt.bar(
    classes,
    counts,
    color=colors[:len(classes)],
    edgecolor="black",
    linewidth=2,
    width=0.6
)
for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 5,
        int(bar.get_height()),
        ha="center",
        fontsize=11,
        fontweight="bold"
    )
plt.title(
    "Distribution of Predicted Classes",
    fontsize=18,
    fontweight="bold"
)
plt.xlabel(
    "Predicted Class",
    fontsize=13,
    fontweight="bold"
)
plt.ylabel(
    "Number of Samples",
    fontsize=13,
    fontweight="bold"
)
plt.grid(
    axis="y",
    linestyle="--",
    alpha=0.5
)
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
plt.tight_layout()
plt.show()

"""**Actual vs Predicted Comparison**"""

from collections import Counter
actual_count = Counter(y_test)
predicted_count = Counter(y_pred)
classes = sorted(set(actual_count.keys()) | set(predicted_count.keys()))
actual_values = [actual_count.get(c, 0) for c in classes]
predicted_values = [predicted_count.get(c, 0) for c in classes]
x = np.arange(len(classes))
width = 0.35
plt.figure(figsize=(9,6))
bars1 = plt.bar(
    x - width/2,
    actual_values,
    width,
    label="Actual",
    color="royalblue",
    edgecolor="black"
)
bars2 = plt.bar(
    x + width/2,
    predicted_values,
    width,
    label="Predicted",
    color="orange",
    edgecolor="black"
)

for bar in bars1:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 5,
        int(bar.get_height()),
        ha="center",
        fontsize=10,
        fontweight="bold"
    )
for bar in bars2:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 5,
        int(bar.get_height()),
        ha="center",
        fontsize=10,
        fontweight="bold"
    )
plt.title(
    "Actual vs Predicted Class Distribution",
    fontsize=18,
    fontweight="bold"
)
plt.xlabel(
    "Class Labels",
    fontsize=13,
    fontweight="bold"
)
plt.ylabel(
    "Number of Samples",
    fontsize=13,
    fontweight="bold"
)
plt.xticks(x, [f"Class {c}" for c in classes], fontsize=11)
plt.legend(fontsize=11)
plt.grid(axis="y", linestyle="--", alpha=0.5)
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
plt.tight_layout()
plt.show()

"""**Model Evaluation**"""

# Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy :", round(accuracy, 4))

# Precision, Recall & F1-Score
from sklearn.metrics import precision_score, recall_score, f1_score
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
print("Precision :", round(precision, 4))
print("Recall    :", round(recall, 4))
print("F1-Score  :", round(f1, 4))

"""**Model Evaluation (Bar Chart)**"""

# Evaluation Metrics
metrics = ["Accuracy", "Precision", "Recall", "F1-Score"]
values = [
    accuracy * 100,
    precision * 100,
    recall * 100,
    f1 * 100
]
colors = ["royalblue", "darkorange", "seagreen", "crimson"]
plt.figure(figsize=(9,6))
bars = plt.bar(
    metrics,
    values,
    color=colors,
    edgecolor="black",
    linewidth=1,
    width=0.3
)
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.8,
        f"{height:.2f}%",
        ha="center",
        fontsize=11,
        fontweight="bold"
    )
plt.title(
    "KNN Model Evaluation Metrics",
    fontsize=18,
    fontweight="bold"
)
plt.xlabel(
    "Evaluation Metrics",
    fontsize=13,
    fontweight="bold"
)
plt.ylabel(
    "Score (%)",
    fontsize=13,
    fontweight="bold"
)
plt.ylim(0, 110)
plt.grid(
    axis="y",
    linestyle="--",
    alpha=0.5
)
ax = plt.gca()
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
plt.tight_layout()
plt.show()

"""**Classification Report**"""

report = classification_report(y_test, y_pred)
print("Classification Report")
print(report)

"""Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

"""**Confusion Matrix Graph**"""

class_names = ["Sweet", "Salty", "Sour", "Spicy"]
plt.figure(figsize=(8,6))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names,
    linewidths=1,
    linecolor="black"
)
plt.title("Confusion Matrix", fontsize=18, fontweight="bold")
plt.xlabel("Predicted Label", fontsize=13, fontweight="bold")
plt.ylabel("Actual Label", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

